# Generated by Django 4.2.7 on 2025-03-31 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_filme_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.genero'),
        ),
    ]
