<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-03-31 19:40
=======
# Generated by Django 5.1.7 on 2025-03-31 19:26
>>>>>>> eb3e681827ada180133916620ee3ac2c19629600

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('sistema', '0003_alter_filme_genero'),
=======
        ('sistema', '0003_filme_genero'),
>>>>>>> eb3e681827ada180133916620ee3ac2c19629600
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m'),
        ),
    ]
