# Generated by Django 5.1.7 on 2025-05-07 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('estudio', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.genero')),
            ],
        ),
    ]
